feat: add-item-requests
Truel0ve/java-shareit pull request #4
Opened 2023-05-09 19:12 UTC by Truel0ve

2023-05-10 02:21 UTC, EvgenyKoptubenko commented
Если есть желание, попробуй использовать параметризованные тесты, чтобы сократить количество кода
https://www.baeldung.com/parameterized-tests-junit-5

2023-05-10 02:27 UTC, EvgenyKoptubenko commented
Если добавить два одинаковых пользователя, то приходит сообщение об ошибке, в котором написано, что используется hibernate
{
	"error": "org.hibernate.exception.ConstraintViolationException: could not execute statement"
}
Желательно не показывать из чего сделано приложение, т.к. это может привести к потенциальным уязвимостям.

2023-05-10 02:29 UTC, EvgenyKoptubenko commented
Зависимость <groupId>com.h2database</groupId> повторяется два раза

2023-05-10 02:30 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Есть предложение попробовать параметризованные тесты, если есть желание

2023-05-10 19:01 UTC, Truel0ve commented
Доработал код:
1. Добавил параметризованные тесты, где они уместны.
2. Исправил сообщение об ошибке при создании второго одинакового пользователя.
3. Удалил лишнюю зависимость из pom.xml.

2023-05-11 02:12 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо большое

2023-05-11 22:03 UTC, merged